# Generated by Django 5.1.4 on 2024-12-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calorieentry',
            name='calorie_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
