# Generated by Django 5.1.4 on 2024-12-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_calorieentry_calorie_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calorieentry',
            name='calorie_limit',
        ),
        migrations.AddField(
            model_name='user',
            name='calorie_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
